export const navigation = [
  { name: 'Dashboard', href: '/', current: false },
  { name: 'Team', href: '/team', current: false },
  { name: 'Projects', href: '/projects', current: false },
  { name: 'Contact Us', href: '/contact-us', current: false },
]

export const ratingRanges = [
  {
    value: 0,
    title: '0-2',
    start: 0,
    end: 2,
  },
  {
    value: 1,
    title: '2-4',
    start: 2,
    end: 4,
  },
  {
    value: 2,
    title: '4-6',
    start: 4,
    end: 6,
  },
  {
    value: 3,
    title: '6-8',
    start: 6,
    end: 8,
  },
  {
    value: 4,
    title: '8-10',
    start: 8,
    end: 10,
  },
]

export const moviesStatic = [
  {
    id: 2166063,
    title: 'Everest',
    summary:
      'An international team of climbers ascends Mt. Everest in the spring of 1996. The film depicts their lengthy preparations for the climb, their trek to the summit, and their successful return to Base Camp. It also shows many of the challenges the group faced, including avalanches, lack of oxygen, treacherous ice walls, and a deadly blizzard.',
    imageUrl: 'https://cdn.watchmode.com/posters/02166063_poster_w185.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=1khEBbx1xbU',
    year: 1998,
    rating: 7.4,
    categories: ['Documentary'],
  },
  {
    id: 1126150,
    title: 'Everest',
    summary:
      'Inspired by the incredible events surrounding a treacherous attempt to reach the summit of the world\'s highest mountain, "Everest" documents the awe-inspiring journey of two different expeditions challenged beyond their limits by one of the fiercest snowstorms ever encountered by mankind. Their mettle tested by the harshest of elements found on the planet, the climbers will face nearly impossible obstacles as a lifelong obsession becomes a breathtaking struggle for survival.',
    imageUrl: 'https://cdn.watchmode.com/posters/01126150_poster_w185.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=79Q2rrQlPW4',
    year: 2015,
    rating: 7,
    categories: ['Adventure', 'Drama', 'History'],
  },
  {
    id: 1126162,
    title: 'エヴェレスト 神々の山嶺',
    summary:
      "Makoto Fukamachi (Junichi Okada) is a Japanese cameraman. He finds an old camera on a backstreet of Nepal. The camera might possibly solve the mystery of whether George Mallory became the first person to successfully climb Mount Everest on June 8, 1924 or not.  Pursuing the old camera's past, Makoto Fukamachi meets legendary Alpinist Joji Habu (Hiroshi Abe). Joji Habu is isolated from other people because of his reckless and thoughtless personality.",
    imageUrl: 'https://cdn.watchmode.com/posters/01126162_poster_w185.jpg',
    videoUrl: '',
    year: 2016,
    rating: 5.7,
    categories: ['Adventure', 'Drama', 'Mystery'],
  },
  {
    id: 339106,
    title: 'Everest: Beyond the Limit',
    summary:
      'Everest: Beyond the Limit is a Discovery Channel reality television series about yearly attempts to summit Mount Everest organized and led by New Zealander Russell Brice.',
    imageUrl: 'https://cdn.watchmode.com/posters/0339106_poster_w185.jpg',
    videoUrl: '',
    year: 2006,
    rating: 8.3,
    categories: ['Documentary'],
  },
  {
    id: 1638638,
    title: 'Everest',
    summary:
      'In 1921, mountaineer George Mallory is picked by Arthur Hinks of the Royal Geographic Society to scale the previously unconquerable Mount Everest. Following World War I, the fading British empire is desperate for a victory, but for Mallory and his rival, the eccentric Aussie George Finch, the challenge has nothing to do with patriotism, instead it is a singular test of self.',
    imageUrl: 'https://cdn.watchmode.com/posters/01638638_poster_w185.jpg',
    videoUrl: '',
    year: null,
    rating: null,
    categories: ['Adventure', 'Drama', 'History'],
  },
  {
    id: 436721,
    title: 'Everest: The Death Zone',
    summary:
      "Get ready for a (literally) breathtaking trek up Mt. Everest, from Base Camp at 17,600 feet; through the chilling, corpse-strewn Death Zone; to the very pinnacle of the the Earth, five and a half miles above sea level. For those brave souls who survive the harrowing climb to the top of the world, it is a transformative experience. But can the excruciating ascent—through frigid cold, blasting wind, blinding sun, and severe lack of oxygen—cause permanent, damaging changes to the human brain and body? In the wake of the 1996 disaster that took eight climbers in a single day, scientists follow a team of hikers to measure, for the first time ever, the toll high-altitude climbing takes on the heart, lungs, blood, and brain. Why do seemingly rational people make poor, sometimes fatal decisions as they approach the peak? And the danger doesn’t end there—as NOVA discovers during the descent, when one climber's respiratory illness takes a terrifying turn on the isolated mountainside.",
    imageUrl: 'https://cdn.watchmode.com/posters/0436721_poster_w185.jpg',
    videoUrl: '',
    year: 1998,
    rating: 7.3,
    categories: ['Documentary'],
  },
  {
    id: 1126161,
    title: 'Everest: The South West Face',
    summary: 'Documentary directed by Neil Armstrong.',
    imageUrl: 'https://cdn.watchmode.com/posters/01126161_poster_w185.jpg',
    videoUrl: '',
    year: 2017,
    rating: null,
    categories: ['Documentary'],
  },
  {
    id: 4155890,
    title: 'Everest Avalanche Tragedy',
    summary:
      'Unprecedented access and eyewitness accounts from the rescue and recovery that took place after the avalanche struck the Khumbu Icefall, just above Mt. Everest base camp, during the morning of Friday, April 18, killing 13 and leaving three missing.',
    imageUrl: 'https://cdn.watchmode.com/posters/04155890_poster_w185.jpg',
    videoUrl: '',
    year: 2014,
    rating: null,
    categories: ['Documentary'],
  },
  {
    id: 2732092,
    title: 'Everest – Juzek Psotka',
    summary: null,
    imageUrl: 'https://cdn.watchmode.com/posters/02732092_poster_w185.jpg',
    videoUrl: '',
    year: 2009,
    rating: null,
    categories: ['Documentary'],
  },
  {
    id: 1502509,
    title: 'Everest: Shooting the Impossible',
    summary: null,
    imageUrl: 'https://cdn.watchmode.com/posters/01502509_poster_w185.jpg',
    videoUrl: '',
    year: 2011,
    rating: null,
    categories: [],
  },
  {
    id: 56114,
    title: 'Everest',
    summary:
      "Based on the true story of the first Canadians to ever make it to the top of the world's tallest and most historic peak. A proud moment for Canadians and an adventure that is filled with bitterness, broken relationships and the bodies of four dead men.",
    imageUrl: 'https://cdn.watchmode.com/posters/056114_poster_w185.jpg',
    videoUrl: '',
    year: 2007,
    rating: 5.8,
    categories: ['Drama'],
  },
  {
    id: 4149439,
    title: 'National Geographic - Everest 50 Years on the Mountain',
    summary:
      "In 1953, Sir Edmund Hillary & Tenzing Norgay made history as the first people to reach the top of Everest. Now, 50 years later, three sons of Everest's most celebrated climbers return to the mountain to challenge it again. Join their journey as they brave the elements and face death to climb 29,000 feet of wind-blasted rock and ice. And, relive the dramatic history of Everest from great triumphs to deadly tragedies, enduring rivalries and the unsung role of the Sherpa people - as National Geographic exposes the untold stories that lurk in the mountain's epic shadow and takes you on THE ultimate Everest experience.",
    imageUrl: 'https://cdn.watchmode.com/posters/04149439_poster_w185.jpg',
    videoUrl: '',
    year: 2003,
    rating: null,
    categories: ['Documentary'],
  },
  {
    id: 1669088,
    title: 'Everest: A Climb for Peace',
    summary:
      'Orlando Bloom narrates this documentary that places the majestic mountain at the center of the sometimes differing aspirations of the peoples around it.',
    imageUrl: 'https://cdn.watchmode.com/posters/01669088_poster_w185.jpg',
    videoUrl: '',
    year: 2007,
    rating: null,
    categories: [],
  },
  {
    id: 56115,
    title: 'Everest Rescue',
    summary:
      'Journeys to the tops of the treacherous Everest Himalayan Mountains, highlighting the work of a rare breed of pilots who put their lives on the line to save those facing certain death. Featuring exclusive access to a group of diverse helicopter pilots as they manage emergency calls during the climbing season as well as intimate interviews with them and their loved ones.',
    imageUrl: 'https://cdn.watchmode.com/posters/056115_poster_w185.jpg',
    videoUrl: '',
    year: 2017,
    rating: 7.7,
    categories: ['Documentary', 'Reality'],
  },
  {
    id: 4144999,
    title: 'Everest: The Mystery of Mallory and Irvine',
    summary:
      'NOVA documentary inquiring into the fate of early Everest explorers George Mallory and Sandy Irvine',
    imageUrl: 'https://cdn.watchmode.com/posters/04144999_poster_w185.jpg',
    videoUrl: '',
    year: 1992,
    rating: null,
    categories: ['Documentary'],
  },
  {
    id: 1676814,
    title: 'Everest – A Graphic Novel Opera',
    summary:
      'Based on the tragic 1996 Mt. Everest disaster, the opera focuses on three climbers as they attempt the ill-fated summit. A new genre, the animated graphic novel puts you inside the pages as the tale drives on.',
    imageUrl: 'https://cdn.watchmode.com/posters/01676814_poster_w185.jpg',
    videoUrl: '',
    year: 2021,
    rating: null,
    categories: ['Animation', 'Drama', 'Music'],
  },
  {
    id: 1126155,
    title: 'Everest Unmasked',
    summary:
      'Italian and Austrian mountaineers Reinhold Messner and Peter Habeler become the first humans to climb Mount Everest without supplementary oxygen.',
    imageUrl: 'https://cdn.watchmode.com/posters/01126155_poster_w185.jpg',
    videoUrl: '',
    year: 1979,
    rating: 7.6,
    categories: ['Documentary'],
  },
  {
    id: 4152903,
    title: 'Everest the Hard Way',
    summary:
      'The classic expedition documentary of the 1975 British Expedition led by Chris Bonington up the South West Face of Everest. The summit was reached by Doug Scott and Dougal Haston followed by an epic bivouac just below the summit. Sadly mountaineer and cameraman Mick Burke died near the summit a day later. Peter Boardman and Pertemba summitted a few days later and made a harrowing descent, finding the top of the fixed ropes only by chance. In many ways, this films records both the end of an era the of big British national expeditions and is the harbinger of a the new alpine style in the Himalaya.',
    imageUrl: 'https://cdn.watchmode.com/posters/04152903_poster_w185.jpg',
    videoUrl: '',
    year: 1975,
    rating: null,
    categories: ['Documentary'],
  },
  {
    id: 1697827,
    title: 'Everest Without Oxygen',
    summary: null,
    imageUrl: 'https://cdn.watchmode.com/posters/01697827_poster_w185.jpg',
    videoUrl: '',
    year: 2020,
    rating: null,
    categories: ['Documentary'],
  },
  {
    id: 1675895,
    title: 'Everest - najťažšia cesta',
    summary: null,
    imageUrl: 'https://cdn.watchmode.com/posters/01675895_poster_w185.jpg',
    videoUrl: '',
    year: 2020,
    rating: null,
    categories: ['Documentary'],
  },
  {
    id: 339105,
    title: 'Everest Air',
    summary:
      'The real-life adventures of a high-altitude helicopter rescue team patrolling Mount Everest are followed in this series, which begins with life and limb being risked to extract two separate injured climbers, both from 21,000 feet. Also: The ARS team provide emergency medical relief to a local boy suffering from a potentially fatal condition.',
    imageUrl: 'https://cdn.watchmode.com/posters/0339105_poster_w185.jpg',
    videoUrl: '',
    year: 2016,
    rating: null,
    categories: ['Documentary', 'Reality'],
  },
]
